# Generated by Django 4.2.9 on 2026-02-08 02:52

import apps.personnel.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOutPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_no', models.CharField(max_length=50, unique=True, verbose_name='警号')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='姓名')),
                ('id_card', models.CharField(blank=True, max_length=18, verbose_name='身份证号')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.personnel.models.avatar_upload_path, verbose_name='蓝底照片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在职')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('binduser', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_out_persons', to=settings.AUTH_USER_MODEL, verbose_name='关联管理员')),
            ],
            options={
                'verbose_name': '出库人员',
                'verbose_name_plural': '出库人员',
                'db_table': 'pm_stock_out_person',
                'ordering': ['-created_at'],
            },
        ),
    ]
